### ISSUE TITLE
Devide operations errors

### ISSUE THREAD

**Issue by svolga** [mdmsoft/yii2-captcha#5]
Captcha not valid works with devide operations.
It always shows an error. How can it be fixed? 

Screenshot:
http://joxi.ru/eAOD89Ph4az1pr

I have to comment 
        'mdm\captcha\equations\Division',
in classes.php

**Comment by mdmunir** [comment]
Please check again with new commit

**Comment by svolga** [comment]
Thank you, it works correctly now.
